#!/usr/bin/with-contenv bash
set -e

RSYSLOG_CONF="${RSYSLOG_CONF:-/etc/rsyslog.conf}";
RSYSLOG_ARGS="${RSYSLOG_ARGS:- -n}";

exec \
    rsyslogd \
    -f ${RSYSLOG_CONF} \
    ${RSYSLOG_ARGS} \
    ;
