ARG DOCKERSRC=frommakefile
#
FROM ${DOCKERSRC}
#
ARG PUID=1000
ARG PGID=1000
#
RUN set -xe \
    && addgroup -g ${PGID} -S alpine \
    && adduser -u ${PUID} -G alpine -h /home/alpine -D alpine \
    && apk add --no-cache --purge -uU \
        logrotate \
        rsyslog \
        rsyslog-tls \
        rsyslog-relp \
        rsyslog-mmjsonparse \
        rsyslog-mmutf8fix \
        tzdata \
    && rm -rf /var/cache/apk/* /tmp/*
#
COPY root/ /
#
VOLUME /config/ /var/log/ /var/spool/rsyslog
#
EXPOSE 2514 514/tcp 514/udp
#
ENTRYPOINT ["/init"]
