#!/bin/sh

if [ -f /etc/conf.d/logrotate ]; then
	. /etc/conf.d/logrotate
fi

if [ -x /usr/bin/cpulimit ] && [ -n "$CPULIMIT" ]; then
	_cpulimit="/usr/bin/cpulimit --limit=$CPULIMIT"
fi

LOGROTATE_CONF=${LOGROTATE_CONF:-/etc/logrotate.conf}
LOGROTATE_STATE=${LOGROTATE_STATE:-/config/logrotate.state}

s6-setuidgid ${PUID}:${PGID} $_cpulimit /usr/sbin/logrotate -s ${LOGROTATE_STATE} -l syslog ${LOGROTATE_CONF}
EXITVALUE=$?
if [ $EXITVALUE != 0 ]; then
    /usr/bin/logger -t logrotate "ALERT exited abnormally with [$EXITVALUE]"
fi
exit 0
